#!/usr/bin/env bash
# Concatenates all migrations into supabase/bundle.sql for one-shot application in the Supabase SQL editor.
set -euo pipefail
out=supabase/bundle.sql
{
  echo "-- GENERATED by scripts/bundle-migrations.sh — do not edit. Apply once to a fresh Supabase project"
  echo "-- AFTER enabling the PostGIS extension (Database → Extensions → postgis)."
  for f in supabase/migrations/*.sql; do echo; echo "-- ===== $f ====="; cat "$f"; done
} > "$out"
echo "wrote $out ($(wc -l < "$out") lines)"
